name: Hello World Training Workflow

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the User
        run: echo "Hello World!"
        
      - name: List files in the current directory
        run: ls -l

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: List files after checkout
        run: ls -l

